import { env } from 'cloudflare:workers';

export const {
	GITHUB_WEBHOOK_SECRET,

	PROFILE_REPOSITORY_ID,
	PROFILE_WEBHOOK_URL,

	VANGUARD_REPOSITORY_ID,
	VANGUARD_WEBHOOK_URL,

	WEBHOOKS_REPOSITORY_ID,
	WEBHOOKS_WEBHOOK_URL,

	WEBSITE_REPOSITORY_ID,
	WEBSITE_WEBHOOK_URL,
} = env;
