import { createResponse } from '#/utils/createResponse.js';
import {
	INTERNAL_SERVER_ERROR_STATUS_CODE,
	INTERNAL_SERVER_ERROR_STATUS_TEXT,
	METHOD_NOT_ALLOWED_STATUS_CODE,
	METHOD_NOT_ALLOWED_STATUS_TEXT,
	NO_CONTENT_STATUS_CODE,
	NOT_FOUND_STATUS_CODE,
	NOT_FOUND_STATUS_TEXT,
	OK_STATUS_CODE,
	OK_STATUS_TEXT,
	UNAUTHORIZED_STATUS_CODE,
	UNAUTHORIZED_STATUS_TEXT,
	UNPROCESSABLE_CONTENT_STATUS_CODE,
	UNPROCESSABLE_CONTENT_STATUS_TEXT,
} from './HttpStatus.js';

export const INTERNAL_SERVER_ERROR_RESPONSE = () =>
	createResponse(INTERNAL_SERVER_ERROR_STATUS_CODE, INTERNAL_SERVER_ERROR_STATUS_TEXT);

export const METHOD_NOT_ALLOWED_RESPONSE = () =>
	createResponse(METHOD_NOT_ALLOWED_STATUS_CODE, METHOD_NOT_ALLOWED_STATUS_TEXT);

export const NO_CONTENT_RESPONSE = () =>
	createResponse(NO_CONTENT_STATUS_CODE, NOT_FOUND_STATUS_TEXT);

export const NOT_FOUND_RESPONSE = () =>
	createResponse(NOT_FOUND_STATUS_CODE, NOT_FOUND_STATUS_TEXT);

export const OK_RESPONSE = () => createResponse(OK_STATUS_CODE, OK_STATUS_TEXT);

export const UNAUTHORIZED_RESPONSE = () =>
	createResponse(UNAUTHORIZED_STATUS_CODE, UNAUTHORIZED_STATUS_TEXT);

export const UNPROCESSABLE_CONTENT_RESPONSE = () =>
	createResponse(UNPROCESSABLE_CONTENT_STATUS_CODE, UNPROCESSABLE_CONTENT_STATUS_TEXT);
